# Generated by Django 6.0.2 on 2026-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_quantity_alter_customer_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Complete'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
